Orders/OrdersSystem/Web/OrdersSystem.Web/Controllers/InOrdersController.cs
namespace OrdersSystem.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;

    using Common;
    using Microsoft.AspNet.Identity;
    using Models;    
    using Ninject;
    using OrdersSystem.Services.Contracts;
    using OrdersSystem.Web.Infrastructure.Mapping;
    using OrdersSystem.Web.ViewModels.InOrders;

    public class InOrdersController : BaseController
    {
        [Inject]
        public IInOrdersServices InOrdersServices { get; set; }

        [Inject]
        public ICustomersServices CustomersSurvices { get; set; }

        [Inject]
        public IDevicesServices DevicesServices { get; set; }

        [Inject]
        public IUsersServices UsersServices { get; set; }

        [Inject]
        public IRolesServices RolesServices { get; set; }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + ", " + GlobalConstants.BossRoleName + ", " + GlobalConstants.WorkerRoleName)]
        public ActionResult Index()
        {
            var inOrders = InOrdersServices
                .GetAll()
                .Where(x => x.IsRepair == false)
                .To<InOrderViewModel>();

            return View(inOrders);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + ", " + GlobalConstants.BossRoleName + ", " + GlobalConstants.WorkerRoleName)]
        public ActionResult Details(int id)
        {
            var inOrder = this.InOrdersServices.GetById(id);
            if (inOrder == null)
            {
                return this.View("Error");
            }

            var viewModel = this.Mapper.Map<InOrderViewModel>(inOrder);

            return this.View(viewModel);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + ", " + GlobalConstants.BossRoleName)]
        [HttpGet]
        public ActionResult Create()
        {
            var viewModel = new InOrderInputModel();
            viewModel.Customers = this.CustomersSurvices
                .GetAll()
                .Select(c => new SelectListItem()
                {
                    Text = c.Name,
                    Value = c.Id.ToString()
                })
                .ToList();
            viewModel.Devices = this.DevicesServices
                .GetAll()
                .Select(d => new SelectListItem()
                {
                    Text = d.Name,
                    Value = d.Id.ToString()
                })
                .ToList();

            var workerRoleId = this.RolesServices.GetRoleId(GlobalConstants.WorkerRoleName);

            viewModel.Workers = this.UsersServices
                .GetAll()
                .Where(w => w.Roles.Any(x => x.RoleId == workerRoleId))
                .Select(w => new SelectListItem()
                {
                    Text = w.UserName,
                    Value = w.Id.ToString()
                })
                .ToList();            
           
            return this.View(viewModel);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + ", " + GlobalConstants.BossRoleName)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(InOrderInputModel model)
        {
            if (this.ModelState.IsValid)
            {
                model.IsRepair = false;
                model.StartDate = DateTime.Now;
                model.AuthorId = User.Identity.GetUserId();
                var newInOrder = this.Mapper.Map<InOrder>(model);
                this.InOrdersServices.Create(newInOrder);

                TempData["Success"] = GlobalConstants.InOrderCreateNotify;
                return this.RedirectToAction("Index");
            }

            return this.View(model);            
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + ", " + GlobalConstants.BossRoleName)]
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var inOrder = this.InOrdersServices.GetById(id);
            if (inOrder == null)
            {
                return this.View("Error");
            }

            var viewModel = this.Mapper.Map<InOrderEditViewModel>(inOrder);

            viewModel.Customers = this.CustomersSurvices
                .GetAll()
                .Select(c => new SelectListItem()
                {
                    Text = c.Name,
                    Value = c.Id.ToString()
                })
                .ToList();
            viewModel.Devices = this.DevicesServices
                .GetAll()
                .Select(d => new SelectListItem()
                {
                    Text = d.Name,
                    Value = d.Id.ToString()
                })
                .ToList();

            var workerRoleId = this.RolesServices.GetRoleId(GlobalConstants.WorkerRoleName);

            viewModel.Workers = this.UsersServices
                .GetAll()
                .Where(w => w.Roles.Any(x => x.RoleId == workerRoleId))
                .Select(w => new SelectListItem()
                {
                    Text = w.UserName,
                    Value = w.Id.ToString()
                })
                .ToList();

            return this.View(viewModel);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + ", " + GlobalConstants.BossRoleName)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(InOrderEditViewModel model)
        {
            if (this.ModelState.IsValid)
            {
                var inOrder = this.Mapper.Map<InOrder>(model);
                this.InOrdersServices.Update(model.Id, inOrder);
                TempData["Success"] = GlobalConstants.InOrderUpdateNotify;
                return this.RedirectToAction("Details", new { id = model.Id });
            }

            return this.View(model);           
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + ", " + GlobalConstants.BossRoleName + ", " + GlobalConstants.WorkerRoleName)]
        [HttpGet]
        public ActionResult GetFullDescription(int id)
        {
            var inOrder = this.InOrdersServices.GetById(id);
            if (inOrder == null)
            {
                return this.View("Error");
            }

            var description = inOrder.Description;

            return this.Content(description);
        }

        [Authorize(Roles = GlobalConstants.WorkerRoleName)]
        [HttpPost]
        public ActionResult UpdateStatus(int id, InOrderViewModel model)
        {
            var inOrder = this.InOrdersServices.GetById(id);
            if (inOrder == null)
            {
                return this.View("Error");
            }

            inOrder.Status = model.Status;
            this.InOrdersServices.UpdateStatus(id, inOrder);
            var content = model.Status;
            return this.Content(content.ToString());
        }
    }
}

Orders/OrdersSystem/Web/OrdersSystem.Web/Controllers/OutOrdersController.cs
namespace OrdersSystem.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;

    using Common;
    using Microsoft.AspNet.Identity;
    using Models;
    using Ninject;
    using OrdersSystem.Web.Infrastructure.Mapping;
    using Services.Contracts;
    using ViewModels.OutOrders;

    public class OutOrdersController : BaseController
    {
        [Inject]
        public IOutOrdersServices OutOrdersServices { get; set; }

        [Inject]
        public IUsersServices UsersServices { get; set; }

        [Inject]
        public ISuppliersServices SuppliersServices { get; set; }

        [Inject]
        public IRolesServices RolesServices { get; set; }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + ", " + GlobalConstants.BossRoleName + ", " + GlobalConstants.WorkerRoleName)]
        public ActionResult Index()
        {
            var outOrders = this.OutOrdersServices
                .GetAll()
                .To<OutOrderViewModel>();

            return View(outOrders);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + ", " + GlobalConstants.BossRoleName + ", " + GlobalConstants.WorkerRoleName)]
        [HttpGet]
        public ActionResult Details(int id)
        {
            var outOrder = this.OutOrdersServices.GetById(id);
            if (outOrder == null)
            {
                return this.View("Error");
            }

            var viewModel = this.Mapper.Map<OutOrderViewModel>(outOrder);

            return this.View(viewModel);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + ", " + GlobalConstants.BossRoleName)]
        [HttpGet]
        public ActionResult Create()
        {
            var newOrder = new OutOrderInputModel();

            newOrder.Suppliers = this.SuppliersServices
                .GetAll()
                .Select(s => new SelectListItem()
                {
                    Text = s.Name,
                    Value = s.Id.ToString()
                })
                .ToList();            

            return this.View(newOrder);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + ", " + GlobalConstants.BossRoleName)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OutOrderInputModel model)
        {
            if (this.ModelState.IsValid)
            {
                model.StartDate = DateTime.Now;
                model.AuthorId = User.Identity.GetUserId();
                var newOutOrder = this.Mapper.Map<OutOrder>(model);
                this.OutOrdersServices.Create(newOutOrder);

                TempData["Success"] = GlobalConstants.OutOrderCreateNotify;
                return this.RedirectToAction("Index");
            }

            return this.View(model);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + ", " + GlobalConstants.BossRoleName)]
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var outOrder = this.OutOrdersServices.GetById(id);
            if (outOrder == null)
            {
                return this.View("Error");
            }

            var viewModel = this.Mapper.Map<OutOrderEditViewModel>(outOrder);

            viewModel.Suppliers = this.SuppliersServices
                .GetAll()
                .Select(c => new SelectListItem()
                {
                    Text = c.Name,
                    Value = c.Id.ToString()
                })
                .ToList();

            var workerRoleId = this.RolesServices.GetRoleId(GlobalConstants.WorkerRoleName);

            viewModel.Workers = this.UsersServices
                .GetAll()
                .Where(w => w.Roles.Any(x => x.RoleId == workerRoleId))
                .Select(w => new SelectListItem()
                {
                    Text = w.UserName,
                    Value = w.Id.ToString()
                })
                .ToList();

            return this.View(viewModel);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + ", " + GlobalConstants.BossRoleName)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(OutOrderEditViewModel model)
        {
            if (this.ModelState.IsValid)
            {
                var outOrder = this.Mapper.Map<OutOrder>(model);
                this.OutOrdersServices.Update(model.Id, outOrder);

                TempData["Success"] = GlobalConstants.OutOrderUpdateNotify;
                return this.RedirectToAction("Details", new { id = model.Id });
            }

            return this.View(model);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName + ", " + GlobalConstants.BossRoleName + ", " + GlobalConstants.WorkerRoleName)]
        [HttpGet]
        public ActionResult GetFullDescription(int id)
        {
            var outOrder = this.OutOrdersServices.GetById(id);
            if (outOrder == null)
            {
                return this.View("Error");
            }

            var description = outOrder.Description;

            return this.Content(description);
        }

        [Authorize(Roles = GlobalConstants.WorkerRoleName)]
        [HttpPost]
        public ActionResult UpdateStatus(int id, OutOrderViewModel model)
        {
            var outOrder = this.OutOrdersServices.GetById(id);
            if (outOrder == null)
            {
                return this.View("Error");
            }

            outOrder.Status = model.Status;
            this.OutOrdersServices.UpdateStatus(id, outOrder);
            var content = model.Status;
            return this.Content(content.ToString());
        }
    }
}

Orders/OrdersSystem/Web/OrdersSystem.Web/Views/Shared/_AllDevicesPartial.cshtml
@model IEnumerable<OrdersSystem.Web.Areas.Admin.ViewModels.Devices.DeviceViewModel>
@using GridMvc.Html

@Html.ActionLink("Add New Device", "Add", null, new { @class = "btn btn-primary" })
<br />
<br />
@Html.Grid(Model).Columns(columns =>
{
    columns.Add(x => x.Name).Titled("Name").SetWidth(110);
    columns.Add(x => x.Category.Name).Titled("Category").SetWidth(110);
    columns.Add().Titled("").Encoded(false).Sanitized(false).SetWidth(30)
        .RenderValueAs(x => Html.ActionLink("Edit", "Edit", new { x.Id }, new { @class = "btn btn-primary" }));
    columns.Add().Titled("").Encoded(false).Sanitized(false).SetWidth(30)
        .RenderValueAs(x => Html.ActionLink("Delete", "Delete", new { x.Id }, new { @class = "btn btn-primary" }));
})

Orders/OrdersSystem/Web/OrdersSystem.Web/Views/Shared/_CacheHomePartial.cshtml
@model IEnumerable<OrdersSystem.Web.ViewModels.InOrders.InOrderViewModel>

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <a href="/InOrders/Details/@item.Id">
                            <strong>Customer: </strong>@item.Customer.Name
                        </a>
                    </h3>
                </div>
                <div class="panel-body">
                    <p>
                        <strong>Device Name: </strong>@item.Device.Name
                    </p>
                    <p>
                        <strong>Device Count: </strong>@item.DeviceCount
                    </p>
                    <div>
                        <strong>End Date: </strong>
                        @Html.DisplayFor(m => item.EndDate)
                    </div>
                </div>
            </div>
        </div>
    }
</div>

Orders/OrdersSystem/Web/OrdersSystem.Web/Views/Shared/_CreateNewButtonPartial.cshtml
@if (User.IsInRole("Boss") || User.IsInRole("Admin"))
{
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary" })
}

Orders/OrdersSystem/Web/OrdersSystem.Web/Views/Shared/_EditButtonPartial.cshtml
@if (User.IsInRole("Boss") || User.IsInRole("Admin"))
{
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary" })
}

Orders/OrdersSystem/Web/OrdersSystem.Web/Views/Shared/_Grid.cshtml
 
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

Orders/OrdersSystem/Web/OrdersSystem.Web/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

Orders/OrdersSystem/Web/OrdersSystem.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="System for orders tracking" />
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Orders", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    @if (User.IsInRole("Worker") || User.IsInRole("Admin") || User.IsInRole("Boss"))
                    {
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true">Orders<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Incoming Orders", "Index", "InOrders", new { area = "" }, null)</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Outgoing Orders", "Index", "OutOrders", new { area = "" }, null)</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Repairs", "Index", "Repairs", new { area = "" }, null)</li>
                                <li class="divider"></li>
                            </ul>
                        </li>
                    }
                    @if (User.IsInRole("Admin"))
                    {
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true">Admin<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Users", "Index", "Users", new { area = "Admin" }, null)</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Devices", "Index", "Devices", new { area = "Admin" }, null)</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Categories", "Index", "Categories", new { area = "Admin" }, null)</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Suppliers", "Index", "Suppliers", new { area = "Admin" }, null)</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Customers", "Index", "Customers", new { area = "Admin" }, null)</li>
                                <li class="divider"></li>
                            </ul>
                        </li>                        
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Orders ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/gridmvc")
    @RenderSection("scripts", required: false)
</body>
</html>

Orders/OrdersSystem/Web/OrdersSystem.Web/Views/Shared/_TempDataPartial.cshtml
@if (TempData["Success"] != null)
{
    <div class="alert alert-dismissible alert-success notification col-md-3 pull-right">
        <strong>@TempData["Success"]</strong>
    </div>
}
@if (TempData["Warning"] != null)
{
    <div class="alert alert-dismissible alert-warning notification col-md-3 pull-right" role="alert">
        <strong>@TempData["Warning"]</strong>
    </div>
}